### ISSUE TITLE
Exercise 3: Mixing two approaches

### ISSUE THREAD

**Issue by daraghking** [twilson63/ngTodoPouch#2]
Just seems to me like it is mixing up adding the remaining todos back into an emptied array with removing unwanted todos from the original array.
I changed it to 

``` javascript
$scope.removeDone = function() {
   var allTodos = $scope.todos,
   remainingToDos = [];
   angular.forEach(allTodos, function(todo) {
      if (!todo.done) {
         remainingToDos.push(todo);
      }
   });
   $scope.todos = remainingToDos;
};
```

when I was working through it.
P.S. thanks for the how-to I found it very helpful

**Comment by twilson63** [comment]
Hey Daragh,

Thanks for using the Tutorial I am glad you found it helpful, and you are
absolutely correct, that is a bug!

Thanks again for sharing!

Tom

On Tue, Jul 23, 2013 at 8:52 PM, Daragh King notifications@github.comwrote:

> Just seems to me like it is mixing up adding the remaining todos back into
> an emptied array with removing unwanted todos from the original array.
> I changed it to
> 
> $scope.removeDone = function() {
>    var allTodos = $scope.todos,
>    remainingToDos = [];
>    angular.forEach(allTodos, function(todo) {
>       if (!todo.done) {
>          remainingToDos.push(todo);
>       }
>    });
>    $scope.todos = remainingToDos;};
> 
> when I was working through it.
> P.S. thanks for the how-to I found it very helpful
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/twilson63/ngTodoPouch/issues/2
> .

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-881-2171
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_Yorkhttp://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.
